version: "3"

tasks:
  # build
  # deploy
  # dev
  # dev1
  # install
  # prepare
  # reload
  # stop
  # start
  # status
  # run

  build:
    cmds:
      - go build cmd/main/main.go

  deploy:
    cmds:
      - task prepare
      - task reload
      - task status

  dev:
    cmds:
      - go run cmd/main/main.go -dev 1

  # hr == "hot reload"
  dev-hr:
    cmds:
      - nodemon --exec go run cmd/main/main.go -dev 1 --signal SIGTERM

  install:
    cmds:
      - go install ./...

  prepare:
    cmds:
      - rm main
      - task install
      - task build

  reload:
    cmds:
      - task stop
      - task start

  run-binary:
    cmds:
      - task prepare
      - ./main

  start:
    cmds:
      - sudo service frankmeza start

  status:
    cmds:
      - sudo service frankmeza status

  stop:
    cmds:
      - sudo service frankmeza stop
